version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - dotnet build -c Release ./ItemService/ItemService.csproj
            - dotnet test -c Release ./ItemService.UnitTests/ItemService.UnitTests.csproj --logger trx --results-directory ./testresults
            - dotnet test ./ItemService.UnitTests.MSBuild/ItemService.UnitTests.MSBuild.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./testresults/coverage/
reports:
    UnitTests:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'
    CodeCoverage:
        file-format: COBERTURAXML
        files:
            - '**/*'
        base-directory: './ItemService.UnitTests.MSBuild/testresults/coverage/'   
