version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - dotnet build -c Release ./ItemService/ItemService.csproj
            - dotnet test  ./ItemService.UnitTests/ItemService.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --results-directory ./testresults
reports:
    DotnetTestExamples:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'
